### ISSUE TITLE
Figure out how to automatically fill the entire width of the cell in Jupyter

### ISSUE THREAD

**Issue by rdeits** [rdeits/meshcat-python#10]
(apparently it's not as easy as `width: 100%`)

**Comment by plusk01** [comment]
FYI, I let the `<div>` width be 100% and it seemed to work as expected (assuming I understood the issue correctly):

```python
    def jupyter_cell(self):
        from IPython.display import HTML
        return HTML("""
<div style="height: 400px; width: 100%; overflow-x: auto; overflow-y: hidden; resize: both">
<iframe src="{url}" style="width: 100%; height: 100%; border: none"></iframe>
</div>
```

![image](https://user-images.githubusercontent.com/3934603/45332743-68778d80-b540-11e8-8874-7cffc686bd5d.png)

Tested on Chrome 69 and Firefox 62 on Ubuntu 16.04 with Python 3 and Jupyter 4.4.0.

**Comment by rdeits** [comment]
Oh, excellent! Are you up for making a PR?

**Comment by RussTedrake** [comment]
Looks like the intention was to close this via #23.  Hope it's ok for me to do it.
