### ISSUE TITLE
[doc] Add libzmq windows installation guide in README

### ISSUE THREAD

**Issue by yijiangh** [rdeits/meshcat-python#46]
In the installation section of the README, maybe we can consider adding a pointer to the [Windows binary installer download page](http://zeromq.org/distro:microsoft-windows) for `ZMQ`:

I've tested successfully the following installation sequence on my 64-bit Windows 10:
1. `pip install meshcat`
2. run the binary installer to install ZMQ
3. call `meshcat-server --open` in the terminal to check the installation

**Comment by rdeits** [comment]
Done! Thank you for the suggestion.
