### ISSUE TITLE
support for triangular meshes with vertices and faces

### ISSUE THREAD

**Issue by nitin-ppnp** [rdeits/meshcat-python#51]
Meshcat is awesome. I want to know if I can visualize an arbitrary triangular mesh with vertices and faces. I have code which is generating the mesh online and I want to visualize it using meshcat. Is it possible?

**Comment by kunguz** [comment]
I am seriously considering using meshcat and meshcat-python for my [project](https://github.com/kunguz/odak). Having this support can get me working with meshcat right away.

**Comment by rdeits** [comment]
This should be working as soon as https://github.com/rdeits/meshcat-python/pull/59 is merged! Can you please let me know if that works for your use case?

**Comment by nitin-ppnp** [comment]
Thanks! Works great for me :)
